### ISSUE TITLE
Name parsing

### ISSUE THREAD

**Issue by rcomber** [ResViz/myimpact-bibtex#1]
Name parsing is failing for names with spaces - e.g. 'Le Dantec, C' comes up as 'Le DCAundefined'. Issue may be due to MyImpact not accepting the spacing.

**Comment by sebble** [comment]
Thanks, I'm working on that now.

**Comment by rcomber** [comment]
May also be caused when there are periods in the formatted bibtex.

**Comment by sebble** [comment]
Do you have an example with periods causing a problem?

**Comment by rcomber** [comment]
This one also did not autofill Journal title.

@article{Poole2014,
abstract = {In this paper, we present disruption of household routines as a method to study home technology usage. Using three case studies as guidance, we show how disrupting household practices--either through changing the technology, task or division of labor--can provide valuable insight into current and future technology usage, and can guide the design of future technologies. Based on our case studies, we outline best practices and challenges with respect to the pragmatics of disruptive research methods. RESEARCH HIGHLIGHTSWe present disruption as a method for studying technology use in homes. Grounded in three case studies, we provide best practices for using this method. We address pragmatic and ethical challenges of using disruption as a method.},
author = {Poole, E. S. and Comber, R. and Hoonhout, J.},
doi = {10.1093/iwc/iwu035},
issn = {0953-5438},
journal = {Interacting with Computers},
month = dec,
number = {1},
pages = {13--20},
title = {{Disruption as a Research Method for Studying Technology Use in Homes}},
url = {http://iwc.oxfordjournals.org/content/27/1/13.short http://iwc.oxfordjournals.org/cgi/doi/10.1093/iwc/iwu035},
volume = {27},
year = {2014}
}

**Comment by sebble** [comment]
Thank you, journal title, abstract, and authors with multiple last names
should all be working now.

**Comment by rcomber** [comment]
I have now submitted about 10 publications in about 5 mins. IT WORKS AMAZINGLY!!!

**Comment by sebble** [comment]
This makes me happy.
